FROM node:12-alpine

WORKDIR /usr/src/app

COPY app.yaml .
COPY package.json .
COPY build-server ./build-server
COPY node_modules ./node_modules

ENV PORT 8080
EXPOSE 8080
CMD [ "npm", "run", "start" ]
