FROM node:10-alpine

WORKDIR /usr/src/app

COPY app.yaml .
COPY package.json .
COPY src/.next ./src/.next
COPY public ./public
COPY .next .next
COPY node_modules ./node_modules

EXPOSE 3000
CMD [ "npm", "run", "start" ]
